export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';
export const REMOVE_PRODUCT_FROM_BASKET = 'REMOVE_PRODUCT_FROM_BASKET';
export const UPDATE_PRODUCT_AMOUNT_IN_BASKET = 'UPDATE_PRODUCT_AMOUNT_IN_BASKET';
